name: css
channels:
  - conda-forge
  - defaults
dependencies:
  - backcall=0.1.0
  - blas=1.0
  - ca-certificates=2019.3.9
  - certifi=2019.3.9
  - cycler=0.10.0
  - decorator=4.4.0
  - freetype=2.9.1
  - intel-openmp=2019.3
  - ipykernel=5.1.0
  - ipython=7.5.0
  - ipython_genutils=0.2.0
  - jedi=0.13.3
  - jpeg=9c
  - jupyter_client=5.2.4
  - jupyter_core=4.4.0
  - kiwisolver=1.1.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libpng=1.6.37
  - libsodium=1.0.16
  - libtiff=4.0.10
  - lz4-c=1.8.3
  - matplotlib=3.1.0
  - mkl=2019.3
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - ncurses=6.1
  - nltk=3.4.1
  - numpy=1.16.4
  - numpy-base=1.16.4
  - olefile=0.46
  - openssl=1.1.1b
  - pandas=0.24.2
  - parso=0.4.0
  - patsy=0.5.1
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=5.3.0
  - pip=19.1.1
  - prompt_toolkit=2.0.9
  - ptyprocess=0.6.0
  - pygments=2.4.0
  - pyparsing=2.4.0
  - python=3.6.8
  - python-dateutil=2.8.0
  - pytz=2019.1
  - pyzmq=18.0.0
  - readline=7.0
  - scipy=1.2.1
  - seaborn=0.9.0
  - setuptools=41.0.1
  - six=1.12.0
  - sqlite=3.28.0
  - statsmodels=0.9.0
  - textblob=0.15.3
  - tk=8.6.8
  - tornado=6.0.2
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - wheel=0.33.4
  - wordcloud=1.5.0
  - xz=5.2.4
  - zeromq=4.3.1
  - zlib=1.2.11
  - zstd=1.4.0
prefix: /anaconda3/envs/css
